<div class="entry-content" itemprop="text"><p style="text-align: justify;">This page confirms that this site i.e. NitinBhatia.in strictly adheres to the Google AdSense program policies and Terms &amp; Conditions.</p>
<p style="text-align: justify;">In case of any further information or you have any questions/clarification/queries about privacy policy of this site, please feel free to contact through email at <a href="mailto:info@nitinbhatia.in">info@nitinbhatia.in</a></p>
<p style="text-align: justify;">This privacy policy document highlights the types of personal information is received and collected by NitinBhatia.in and how it is being used.</p>
<p style="text-align: justify;"><strong>Privacy Policy for NitinBhatia.in </strong></p>
<p style="text-align: justify;">The privacy of visitors to NitinBhatia.in is of prime importance to us.</p>
<p style="text-align: justify;">At NitinBhatia.in, we recognize that privacy of your personal information is important. Here is information on what types of personal information we receive and collect when you use and visit NitinBhatia.in, and how we safeguard your information. We never sell your personal information to third parties.</p>
<p style="text-align: justify;"><strong>Log Files</strong></p>
<p style="text-align: justify;">Like many other Web sites, NitinBhatia.in makes use of log files. The information inside the log files includes internet protocol ( IP ) addresses, type of browser, Internet Service Provider ( ISP ), date/time stamp, referring/exit pages and gather demographic information. IP addresses, and other such information are not linked to any information that is personally identifiable.</p>
<p style="text-align: justify;"><strong>Cookies and Web Beacons</strong></p>
<p style="text-align: justify;">As with most other website, NitinBhatia.in does use cookies to store information about visitors preferences, record user-specific information on which pages the user access or visit, customize Web page content based on visitors browser type or other information that the visitor sends via their browser.</p>
<p style="text-align: justify;">Our advertising partners may use cookies and web beacons. These third-party ad servers or ad networks use technology to the advertisements and links that appear on&nbsp;NitinBhatia.in send directly to your browsers. They automatically receive your IP address when this occurs. Other technologies (such as cookies, JavaScript, or Web Beacons) may also be used by the third-party ad networks to measure the effectiveness of their advertisements and / or to personalize the advertising content that you see.</p>
<p style="text-align: justify;">We have no access to or control over these cookies that are used by third-party advertisers.</p>
<p style="text-align: justify;">You should consult the respective privacy policies of these third-party ad servers for more detailed information on their practices as well as for instructions about how to opt-out of certain practices. The privacy policy of NitinBhatia.in does not apply to, and we cannot control the activities of, such other advertisers or web sites.</p>
<p style="text-align: justify;"><strong>DoubleClick DART cookies</strong></p>
<p style="text-align: justify;">We also may use DART cookies for ad serving through Google’s DoubleClick, which places a cookie on your computer when you are browsing the web and visit a site using DoubleClick advertising (including some Google AdSense advertisements). This cookie is used to serve ads specific to you and your interests (”interest based targeting”).</p>
<p style="text-align: justify;">The ads served will be targeted based on your previous browsing history (For example, if you have been viewing sites about visiting Goa, you may see Goa hotel advertisements when viewing a non-related site, such as on a site about Cricket). DART uses “non personally identifiable information”. It does NOT track personal information about you, such as your name, email address, physical address, telephone number, bank account numbers or credit card numbers.</p>
<p style="text-align: justify;">You can opt-out of this ad serving on all sites using this advertising by visiting</p>
<p style="text-align: justify;"><a href="http://www.google.com/policies/technologies/ads/" target="_blank">http://www.google.com/policies/technologies/ads/</a></p>
<p style="text-align: justify;">You can choose to disable or selectively turn off our cookies or third-party cookies in your browser settings, or by managing preferences in programs such as Norton Internet Security. However, this can affect how you are able to interact with our site as well as other websites. This could include the inability to login to services or programs, such as logging into forums or accounts.</p>
<p>Deleting cookies does not mean you are permanently opted out of any advertising program. Unless you have settings that disallow cookies, the next time you visit a site running the advertisements, a new cookie will be added.</p>
<!-- Simple Share Buttons Adder (7.4.18) simplesharebuttons.com --><div id="ssba-classic-2" class="ssba ssbp-wrap left ssbp--theme-1"><div style="text-align:left"><span class="ssba-share-text">Share this...</span><br><a data-site="" class="ssba_facebook_share" href="http://www.facebook.com/sharer.php?u=https://www.nitinbhatia.in/google-adsense-privacy-policy/" target="_blank" rel="nofollow"><img src="https://www.nitinbhatia.in/wp-content/plugins/simple-share-buttons-adder/buttons/somacro/facebook.png" style="width: 35px;" title="Facebook" class="ssba ssba-img" alt="Share on Facebook"><div title="Facebook" class="ssbp-text">Facebook</div></a><a data-site="" class="ssba_google_share" href="https://plus.google.com/share?url=https://www.nitinbhatia.in/google-adsense-privacy-policy/" target="&quot;_blank&quot;" rel="&quot;nofollow&quot;"><img src="https://www.nitinbhatia.in/wp-content/plugins/simple-share-buttons-adder/buttons/somacro/google.png" style="width: 35px;" title="Google+" class="ssba ssba-img" alt="Share on Google+"><div title="Google+" class="ssbp-text">Google+</div></a><a data-site="" class="ssba_twitter_share" href="http://twitter.com/share?url=https://www.nitinbhatia.in/google-adsense-privacy-policy/&amp;text=Google%20Adsense%20Privacy%20Policy%20" target="&quot;_blank&quot;" rel="&quot;nofollow&quot;"><img src="https://www.nitinbhatia.in/wp-content/plugins/simple-share-buttons-adder/buttons/somacro/twitter.png" style="width: 35px;" title="Twitter" class="ssba ssba-img" alt="Tweet about this on Twitter"><div title="Twitter" class="ssbp-text">Twitter</div></a><a data-site="linkedin" class="ssba_linkedin_share ssba_share_link" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=https://www.nitinbhatia.in/google-adsense-privacy-policy/" target="&quot;_blank&quot;" rel="&quot;nofollow&quot;"><img src="https://www.nitinbhatia.in/wp-content/plugins/simple-share-buttons-adder/buttons/somacro/linkedin.png" style="width: 35px;" title="LinkedIn" class="ssba ssba-img" alt="Share on LinkedIn"><div title="Linkedin" class="ssbp-text">Linkedin</div></a><a data-site="email" class="ssba_email_share" href="mailto:?subject=Google%20Adsense%20Privacy%20Policy&amp;body=%20https://www.nitinbhatia.in/google-adsense-privacy-policy/"><img src="https://www.nitinbhatia.in/wp-content/plugins/simple-share-buttons-adder/buttons/somacro/email.png" style="width: 35px;" title="Email" class="ssba ssba-img" alt="Email this to someone"><div title="email" class="ssbp-text">email</div></a></div></div></div>